// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXhMGa7j_R5jOmLQNRRCJ-7bx22CMklII',
    appId: '1:435019503849:web:c22c5490584bd8b7d03878',
    messagingSenderId: '435019503849',
    projectId: 'chat-flutter-dd51e',
    authDomain: 'chat-flutter-dd51e.firebaseapp.com',
    storageBucket: 'chat-flutter-dd51e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBirt0RlyHejrSW4XIRm-HhrGLxWXMIp94',
    appId: '1:435019503849:android:ae045b9434b3ea76d03878',
    messagingSenderId: '435019503849',
    projectId: 'chat-flutter-dd51e',
    storageBucket: 'chat-flutter-dd51e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPjH5hYnpqmlZrpA3RBUWnvjrudE7kpTQ',
    appId: '1:435019503849:ios:041a0183fb4dd9c2d03878',
    messagingSenderId: '435019503849',
    projectId: 'chat-flutter-dd51e',
    storageBucket: 'chat-flutter-dd51e.firebasestorage.app',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPjH5hYnpqmlZrpA3RBUWnvjrudE7kpTQ',
    appId: '1:435019503849:ios:041a0183fb4dd9c2d03878',
    messagingSenderId: '435019503849',
    projectId: 'chat-flutter-dd51e',
    storageBucket: 'chat-flutter-dd51e.firebasestorage.app',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXhMGa7j_R5jOmLQNRRCJ-7bx22CMklII',
    appId: '1:435019503849:web:2da392dc07896fbcd03878',
    messagingSenderId: '435019503849',
    projectId: 'chat-flutter-dd51e',
    authDomain: 'chat-flutter-dd51e.firebaseapp.com',
    storageBucket: 'chat-flutter-dd51e.firebasestorage.app',
  );
}
